export const appConstants = {
    SET_APP_STATE: 'SET_APP_STATE',
};

export const userConstants = {
    INIT_USER: 'INIT_AUTH',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    SAFE_LOGOUT: 'SAFE_LOGOUT',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    SET_USER: 'SET_USER',
    RESET_USER: 'RESET_USER',
};

export const specialsConstants = {
    SPECIAL_DATA_REQUEST_STATUS: 'SPECIAL_DATA_REQUEST_STATUS',
    SPECIAL_LIST_FAILURE: 'SPECIAL_LIST_FAILURE',
    RECEIVED_SPECIAL_LIST: 'RECEIVED_SPECIAL_LIST',
    SPECIAL_SELECTED: 'SPECIAL_SELECTED',
    SPECIAL_ADD_SUCCESS: 'SPECIAL_ADD_SUCCESS',
    SPECIAL_ADD_FAILURE: 'SPECIAL_ADD_FAILURE',
    SPECIAL_UPDATE_SUCCESS: 'SPECIAL_UPDATE_SUCCESS',
    SPECIAL_CLICK_UPDATE_SUCCESS: 'SPECIAL_CLICK_UPDATE_SUCCESS',
    SPECIAL_UPDATE_FAILURE: 'SPECIAL_UPDATE_FAILURE',
};

export const reservationConstants = {
    SPECIAL_ADD_TO_RESERVATION: 'SPECIAL_ADD_TO_RESERVATION',
    SPECIAL_UPDATE_TO_RESERVATION: 'SPECIAL_UPDATE_TO_RESERVATION',
    SPECIAL_DECREASE_FROM_RESERVATION: 'SPECIAL_DECREASE_FROM_RESERVATION',
    SPECIAL_REMOVE_FROM_BAG: 'SPECIAL_REMOVE_FROM_BAG',
    SPECIAL_CLEAR_FROM_BAG: 'SPECIAL_CLEAR_FROM_BAG',

    RECEIVED_RESERVATION_LIST: 'RECEIVED_RESERVATION_LIST',
    RESERVATION_DATA_REQUEST_STATUS: 'RESERVATION_DATA_REQUEST_STATUS',
    RESERVATION_LIST_FAILURE: 'RESERVATION_LIST_FAILURE',
    CENCEL_RESERVATION: 'CENCEL_RESERVATION',
    CONFIRM_RESERVATION: 'CONFIRM_RESERVATION',
};

export const favouriteConstants = {
    RECEIVED_FAVOURITE_LIST: 'RECEIVED_FAVOURITE_LIST',
    FAVOURITE_DATA_REQUEST_STATUS: 'FAVOURITE_DATA_REQUEST_STATUS',
    FAVOURITE_LIST_FAILURE: 'FAVOURITE_LIST_FAILURE',
};

export const restaurantConstants = {
    RESTAURANT_DATA_REQUEST_STATUS: 'RESTAURANT_DATA_REQUEST_STATUS',
    RESTAURANT_DETAILS_FAILURE: 'RESTAURANT_DETAILS_FAILURE',
    RECEIVED_RESTAURANT_DETAILS: 'RECEIVED_RESTAURANT_DETAILS',
    RESTAURANT_LIST_FAILURE: 'RESTAURANT_LIST_FAILURE',
    RECEIVED_RESTAURANT_LIST: 'RECEIVED_RESTAURANT_LIST',
    RESTAURANT_SELECTED: 'RESTAURANT_SELECTED',
    RESTAURANT_ADD_SUCCESS: 'RESTAURANT_ADD_SUCCESS',
    RESTAURANT_ADD_FAILURE: 'RESTAURANT_ADD_FAILURE',
    RESTAURANT_UPDATE_SUCCESS: 'RESTAURANT_UPDATE_SUCCESS',
    RESTAURANT_UPDATE_FAILURE: 'RESTAURANT_UPDATE_FAILURE',

    RECEIVED_RESTAURANT_MENU_LIST: 'RECEIVED_RESTAURANT_MENU_LIST',
    RECEIVED_RESTAURANT_REVIEW_LIST: 'RECEIVED_RESTAURANT_REVIEW_LIST',
    RECEIVED_RESTAURANT_REVIEW_IMAGE_LIST: 'RECEIVED_RESTAURANT_REVIEW_IMAGE_LIST',

    RECEIVED_TODAYS_RESERVATION_LIST: 'RECEIVED_TODAYS_RESERVATION_LIST',
    RECEIVED_PENDING_RESERVATION_LIST: 'RECEIVED_PENDING_RESERVATION_LIST',
    RECEIVED_CONFIRMED_RESERVATION_LIST: 'RECEIVED_CONFIRMED_RESERVATION_LIST',
    RECEIVED_CANCELLED_RESERVATION_LIST: 'RECEIVED_CANCELLED_RESERVATION_LIST',
    RECEIVED_REPORT_RESERVATION_LIST: 'RECEIVED_REPORT_RESERVATION_LIST',
};
